---
- name: Update package libraries based on Linux family
  tags: update_package
  ansible.builtin.command: "{% if linux_family == \"Ubuntu\" %}apt-get update -y --ignore-missing {% elif linux_family == \"Linux\"  %}yum update -y --skip-broken{% endif %}"
  register: log
  ignore_errors: yes
  become: "{{become_root}}"
  async: 300
  poll: 5
- name: Output
  debug: 
    msg: |
     {{linux_family}}
     {% if linux_family == "Ubuntu" %}apt-get update{% elif linux_family == "Linux"  %}yum update{% endif %}
