---
- name: "Playbook to update ubuntu catalog and install tomcat9"
  hosts: localhost
  become: true
  become_method: sudo
  tasks:
    - name: "Update Cache"
      apt:
        update_cache: true
    - name: "Installing Tomcat9"
      apt:
        name: tomcat9
        state: present

